server {
    listen 80 default_server;
    server_name blog.baileys.dev localhost;
    root /usr/share/nginx/html/blog.baileys.dev;
    index index.html;
    error_page 404 /404.html;
    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name baely.au;
    root /usr/share/nginx/html/baely.au;
    index index.html;
    error_page 404 /404.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
