baseURL = 'https://baely.au'
languageCode = 'en-AU'
timeZone = 'Australia/Melbourne'
title = 'Notes and ramblings'
theme = 'shared'
themesDir = "../themes"
enableRobotsTXT = true
buildDrafts = true
disableKinds = ['taxonomy', 'term']

[params]
  homeHeading = "Notes from Bailey."
  mainSection = "notes"
  latestHeading = "Latest notes"
  description = 'Personal notes, rambling, and occasionally longer essays.'
  author = 'Bailey Butler'
  introduction = "My personal notes, rambling, and occasionally longer essays."

[permalinks]
  notes = '/notes/:year-:month-:day/'

[outputs]
  home = ['HTML']
  section = ['HTML', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
      wrapStandAloneImageWithinParagraph = false

[minify]
  minifyOutput = true
